# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

filegroup(
    name = "service",
    srcs = [
        "compiler_gym-gcc-service",
        "gcc_service.py",
    ],
    visibility = ["//visibility:public"],
)
