#! /usr/bin/env python3
#
#  Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
import os

from compiler_gym.envs.gcc import DEFAULT_GCC
from compiler_gym.envs.gcc.service.gcc_service import make_gcc_compilation_session
from compiler_gym.service.runtime import create_and_run_compiler_gym_service

if __name__ == "__main__":
    gcc: str = os.environ.get("CC", DEFAULT_GCC)
    create_and_run_compiler_gym_service(make_gcc_compilation_session(gcc))
