#!/usr/bin/env python3
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
import os
import traceback

from compiler_gym.envs.cgra.service.relative_placement_service import make_cgra_compilation_session
from compiler_gym.service.runtime import create_and_run_compiler_gym_service

if __name__ == "__main__":
    try:
        create_and_run_compiler_gym_service(make_cgra_compilation_session())
    except:
        print(traceback.format_exc())
        raise