# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "architectures",
    srcs = [
        "__init__.py",
        "CGRA.py"
    ],
    visibility = ["//visibility:public"]
)