# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
"""Regression tests generated by fuzzing."""
import difflib
import subprocess

import pytest

from tests.test_main import main

pytest_plugins = [
    "tests.pytest_plugins.llvm",
    "tests.pytest_plugins.common",
]


@pytest.mark.xfail(reason="-separate-const-offset-from-gep", strict=True)
def test_regression_test_const_offset_from_gep(env, tmpwd, llvm_diff, llvm_opt):
    env.reset(benchmark="benchmark://cbench-v1/blowfish")
    env.write_ir("input.ll")
    # FIXME: Removing the -separate-const-offset-from-gep actions from the below
    # commandline "fixes" the test.
    actions = env.commandline_to_actions(
        "opt -objc-arc-apelim -separate-const-offset-from-gep -sancov -indvars -loop-reduce -dse -inferattrs -loop-fusion -dce -break-crit-edges -constmerge -indvars -mem2reg -objc-arc-expand -ee-instrument -loop-reroll -break-crit-edges -separate-const-offset-from-gep -loop-idiom -float2int -dce -float2int -ipconstprop -simple-loop-unswitch -coro-cleanup -early-cse-memssa -strip -functionattrs -objc-arc-contract -sink -loop-distribute -loop-reroll -slsr -separate-const-offset-from-gep input.bc -o output.bc"
    )

    for action in actions:
        _, _, done, info = env.step(action)
        assert not done, info["error_details"]
    env.write_ir("env.ll")

    subprocess.check_call(
        env.commandline(textformat=True),
        env={"PATH": str(llvm_opt.parent)},
        shell=True,
        timeout=60,
    )
    with open("output.ll") as f1, open("env.ll") as f2:
        for line in difflib.unified_diff(f1.readlines()[1:], f2.readlines()[1:]):
            subprocess.check_output(
                [
                    llvm_diff,
                    "output.ll",
                ]
            )


if __name__ == "__main__":
    main()
