# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

py_test(
    name = "compiler_env_test",
    srcs = ["compiler_env_test.py"],
    deps = [
        "//compiler_gym/envs",
        "//tests:test_main",
    ],
)
