# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

py_library(
    name = "tabular_q_eval",
    srcs = ["tabular_q_eval.py"],
    deps = [
        "//examples:tabular_q",
        "//leaderboard/llvm_codesize:eval_policy",
    ],
)
