---
name: Install build dependencies
description: Install build dependencies
runs:
    using: composite
    steps:
        - name: Install dependencies
          run: |
              if [ "$(uname)" = "Darwin" ]; then
                  brew install bazelisk zlib
              else
                  curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64" > bazel
                  chmod +x bazel
                  sudo mv bazel /usr/local/bin/bazel
                  sudo apt-get install -y clang-9 patchelf
              fi
              python -m pip install -U pip wheel
              python -m pip install -r compiler_gym/requirements_build.txt
          shell: bash
          env:
              LDFLAGS: -L/usr/local/opt/zlib/lib
              CPPFLAGS: -I/usr/local/opt/zlib/include
              PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig
