# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

py_library(
    name = "service",
    srcs = [
        "loop_tool_compilation_session.py",
    ],
    visibility = ["//compiler_gym/envs/loop_tool:__subpackages__"],
)
